name: BLAS CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libopenblas-dev

    - name: Build project
      run: make build

    - name: Interface Tests (CBLAS Level 1)
      run: make test

    - name: Performance Benchmark (symm)
      run: make benchmark